# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaBloque3.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import sympy
import sympy as sp
import re
import VentanaBloques


class VentanaBloque3_Class(QtWidgets.QMainWindow):

    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, VentanaBloque3):
        VentanaBloque3.setObjectName("VentanaBloque3")
        VentanaBloque3.resize(800, 592)
        VentanaBloque3.setStyleSheet("background-color: rgb(139, 139, 139);")
        self.centralwidget = QtWidgets.QWidget(VentanaBloque3)
        self.centralwidget.setObjectName("centralwidget")
        self.CmdRegreBloq2 = QtWidgets.QPushButton(self.centralwidget)
        self.CmdRegreBloq2.setGeometry(QtCore.QRect(580, 500, 81, 41))
        self.CmdRegreBloq2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CmdRegreBloq2.setObjectName("CmdRegreBloq2")
        #self.CmdSalirBloq2 = QtWidgets.QPushButton(self.centralwidget)
        #self.CmdSalirBloq2.setGeometry(QtCore.QRect(680, 500, 81, 41))
        #self.CmdSalirBloq2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
#"")
        #self.CmdSalirBloq2.setObjectName("CmdSalirBloq2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 30, 471, 31))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"Border-radius: 10px;")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 100, 331, 91))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(460, 100, 331, 91))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"")
        self.label_5.setObjectName("label_5")
        self.CmdResolver3 = QtWidgets.QPushButton(self.centralwidget)
        self.CmdResolver3.setGeometry(QtCore.QRect(190, 300, 81, 41))
        self.CmdResolver3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CmdResolver3.setObjectName("CmdResolver3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(160, 360, 131, 31))
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"")
        self.label_7.setObjectName("label_7")
        self.TxtDatos = QtWidgets.QLineEdit(self.centralwidget)
        self.TxtDatos.setGeometry(QtCore.QRect(100, 250, 251, 31))
        self.TxtDatos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TxtDatos.setObjectName("TxtDatos")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(190, 210, 81, 31))
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(580, 210, 81, 31))
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"")
        self.label_8.setObjectName("label_8")
        self.CmdResolver4 = QtWidgets.QPushButton(self.centralwidget)
        self.CmdResolver4.setGeometry(QtCore.QRect(590, 300, 81, 41))
        self.CmdResolver4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CmdResolver4.setObjectName("CmdResolver4")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(560, 360, 131, 31))
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"")
        self.label_9.setObjectName("label_9")
        self.TxtDatos_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.TxtDatos_2.setGeometry(QtCore.QRect(500, 250, 251, 31))
        self.TxtDatos_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TxtDatos_2.setObjectName("TxtDatos_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 181, 91))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("logo_tamaño_horizontal.png"))
        self.label_2.setObjectName("label_2")
        self.LblTrinomio = QtWidgets.QLabel(self.centralwidget)
        self.LblTrinomio.setGeometry(QtCore.QRect(110, 410, 221, 41))
        self.LblTrinomio.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.LblTrinomio.setText("")
        self.LblTrinomio.setObjectName("LblTrinomio")
        self.LblSuma = QtWidgets.QLabel(self.centralwidget)
        self.LblSuma.setGeometry(QtCore.QRect(510, 410, 221, 41))
        self.LblSuma.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.LblSuma.setText("")
        self.LblSuma.setObjectName("LblSuma")
        VentanaBloque3.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VentanaBloque3)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        VentanaBloque3.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaBloque3)
        self.statusbar.setObjectName("statusbar")
        VentanaBloque3.setStatusBar(self.statusbar)

        self.CmdResolver3.clicked.connect(self.Resuelve111)
        self.CmdResolver4.clicked.connect(self.Resuelve222)
        self.CmdRegreBloq2.clicked.connect(self.CierraBloque111)

        self.retranslateUi(VentanaBloque3)
        QtCore.QMetaObject.connectSlotsByName(VentanaBloque3)

    def retranslateUi(self, VentanaBloque3):
        _translate = QtCore.QCoreApplication.translate
        VentanaBloque3.setWindowTitle(_translate("VentanaBloque3", "VentanaBloque3"))
        self.CmdRegreBloq2.setText(_translate("VentanaBloque3", "Regresar"))
        #self.CmdSalirBloq2.setText(_translate("VentanaBloque3", "Salir"))
        self.label.setText(_translate("VentanaBloque3", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Trinomio Cuadrado Perfecto y Suma Cubos</span></p><p align=\"center\"><br/></p></body></html>"))
        self.label_4.setText(_translate("VentanaBloque3", "<html><head/><body><p><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff;\">Trinomio Cuadrado Perfecto</span></p><p><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff;\">Ejemplo: x</span><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff; vertical-align:super;\">2 </span><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff;\">+6x+9= (x+3)</span><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff; vertical-align:super;\">2</span></p></body></html>"))
        self.label_5.setText(_translate("VentanaBloque3", "<html><head/><body><p><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff;\">Suma de Cubos</span></p><p><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff;\">Ejemplo: 8x</span><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff; vertical-align:super;\">3</span><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff;\"> +125= (2x+5)(4x</span><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff; vertical-align:super;\">2</span><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff;\"> -10x+25)</span></p></body></html>"))
        self.CmdResolver3.setText(_translate("VentanaBloque3", "Resolver"))
        self.label_7.setText(_translate("VentanaBloque3", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Resultado</span></p><p align=\"center\"><br/></p></body></html>"))
        self.label_6.setText(_translate("VentanaBloque3", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Datos</span></p><p align=\"center\"><br/></p></body></html>"))
        self.label_8.setText(_translate("VentanaBloque3", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Datos</span></p><p align=\"center\"><br/></p></body></html>"))
        self.CmdResolver4.setText(_translate("VentanaBloque3", "Resolver"))
        self.label_9.setText(_translate("VentanaBloque3", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Resultado</span></p><p align=\"center\"><br/></p></body></html>"))


    def Resuelve111(self):
        try:
            # Convertir la expresión ingresada en un objeto sympy
            expresioninicial = self.TxtDatos.text()
            #print ("expresion inicial", expresioninicial)
            expresionsinespacio = expresioninicial.replace(" ", "")
            expresionsinespacio = expresionsinespacio.replace("^", "**")
            expresioncorregida = re.sub(r'([a-zA-Z])(?=[a-zA-Z])', r'\1*', expresionsinespacio)
            #print("expresion corregida 1", expresioncorregida)
            expresioncorregida = re.sub(r'([a-zA-Z])([a-zA-Z])', r'\1*\2', expresioncorregida)
            #print("expresion corregida 2", expresioncorregida)
            expresioncorregida = re.sub(r'(\d+)([a-zA-Z])', r'\1*\2', expresioncorregida)
            #print("expresion corregida 3", expresioncorregida)
            #expresioncorregida = sympy.expand(expresioncorregida)
            solution = sp.factor(expresioncorregida)
            #print("expresion expandida final",solution)
            espaniol = str(solution)
            cadena = espaniol.replace("**", "^")
            cadena = cadena.replace("*", "")
            self.LblTrinomio.setText(cadena)


        except (sp.SympifyError, ValueError) as e:
            print(f"Error al procesar la expresión: {e}")


    def Resuelve222(self):
        try:
            # Convertir la expresión ingresada en un objeto sympy
            expresioninicial = self.TxtDatos_2.text()
            #print(expresioninicial)
            expresionsinespacio = expresioninicial.replace(" ", "")
            #print(expresionsinespacio)
            expresionsinespacio = expresionsinespacio.replace("^", "**")
            #print(expresionsinespacio)
            expresioncorregida = re.sub(r'([a-zA-Z])(?=[a-zA-Z])', r'\1*', expresionsinespacio)
            expresioncorregida = re.sub(r'([a-zA-Z])([a-zA-Z])', r'\1*\2', expresioncorregida)
            #print(expresioncorregida)
            expresioncorregida = re.sub(r'(\d+)([a-zA-Z])', r'\1*\2', expresioncorregida)
            #print(expresioncorregida)
            solution = sympy.factor(expresioncorregida)
            #print("solucion", solution)
            espaniol = str(solution)
            cadena = espaniol.replace("**", "^")
            #print("cadena expuesta", cadena)
            cadena = cadena.replace("*", "")
            self.LblSuma.setText(cadena)

        except (sp.SympifyError, ValueError) as e:
            print(f"Error al procesar la expresión: {e}")

    def CierraBloque111(self):
        self.close()  # Cierra la ventana actual
        self.ventana_principal2 = VentanaBloques.VentanaBloquesClass()  # Crea una nueva instancia de VentanaPrincipal
        self.ventana_principal2.show()  # Muestra la nueva ventana principal



def main():
    app = QtWidgets.QApplication(sys.argv)
    ventana = VentanaBloque3_Class()
    ventana.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    main()
