# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaBloque1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import sympy
import sympy as sp
import re
import VentanaBloques
class VentanaBloque1_Class(QtWidgets.QMainWindow):

    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, VentanaBloque1_2):
        VentanaBloque1_2.setObjectName("VentanaBloque1_2")
        VentanaBloque1_2.resize(789, 599)
        VentanaBloque1_2.setStyleSheet("background-color: rgb(136, 136, 136);")
        self.centralwidget = QtWidgets.QWidget(VentanaBloque1_2)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 10, 461, 51))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"Border-radius: 10px;")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 281, 91))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 200, 81, 31))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"")
        self.label_4.setObjectName("label_4")
        self.TxtDatos2 = QtWidgets.QLineEdit(self.centralwidget)
        self.TxtDatos2.setGeometry(QtCore.QRect(470, 240, 251, 31))
        self.TxtDatos2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TxtDatos2.setObjectName("TxtDatos2")
        self.CmdResolver = QtWidgets.QPushButton(self.centralwidget)
        self.CmdResolver.setGeometry(QtCore.QRect(120, 290, 81, 41))
        self.CmdResolver.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CmdResolver.setObjectName("CmdResolver")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(90, 360, 131, 31))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(460, 90, 261, 91))
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"")
        self.label_6.setObjectName("label_6")
        self.CmdResolver2 = QtWidgets.QPushButton(self.centralwidget)
        self.CmdResolver2.setGeometry(QtCore.QRect(570, 290, 81, 41))
        self.CmdResolver2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CmdResolver2.setObjectName("CmdResolver2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(540, 360, 131, 31))
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(560, 200, 81, 31))
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"")
        self.label_8.setObjectName("label_8")
        self.TxtDatos = QtWidgets.QLineEdit(self.centralwidget)
        self.TxtDatos.setGeometry(QtCore.QRect(40, 240, 251, 31))
        self.TxtDatos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TxtDatos.setObjectName("TxtDatos")
        self.CmdRegresar = QtWidgets.QPushButton(self.centralwidget)
        self.CmdRegresar.setGeometry(QtCore.QRect(650, 500, 81, 41))
        self.CmdRegresar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CmdRegresar.setObjectName("CmdRegresar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, -10, 141, 101))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("logo_tamaño_web_vertical.png"))
        self.label_2.setObjectName("label_2")
        self.LblFactorComun = QtWidgets.QLabel(self.centralwidget)
        self.LblFactorComun.setGeometry(QtCore.QRect(50, 420, 221, 41))
        self.LblFactorComun.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.LblFactorComun.setText("")
        self.LblFactorComun.setObjectName("LblFactorComun")
        self.LblBinomio = QtWidgets.QLabel(self.centralwidget)
        self.LblBinomio.setGeometry(QtCore.QRect(490, 420, 221, 41))
        self.LblBinomio.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.LblBinomio.setText("")
        self.LblBinomio.setObjectName("LblBinomio")
        VentanaBloque1_2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VentanaBloque1_2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 789, 21))
        self.menubar.setObjectName("menubar")
        VentanaBloque1_2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaBloque1_2)
        self.statusbar.setObjectName("statusbar")
        VentanaBloque1_2.setStatusBar(self.statusbar)

        self.CmdResolver.clicked.connect(self.Resuelve1)
        self.CmdResolver2.clicked.connect(self.Resuelve2)
        self.CmdRegresar.clicked.connect(self.CierraBloque1)

        self.retranslateUi(VentanaBloque1_2)
        QtCore.QMetaObject.connectSlotsByName(VentanaBloque1_2)

    def retranslateUi(self, VentanaBloque1_2):
        _translate = QtCore.QCoreApplication.translate
        VentanaBloque1_2.setWindowTitle(_translate("VentanaBloque1_2", "VentanaBloque1"))
        self.label.setText(_translate("VentanaBloque1_2", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Factor Comun y Binomios cuadrados perfectos</span></p></body></html>"))
        self.label_3.setText(_translate("VentanaBloque1_2", "<html><head/><body><p><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff;\">Factor Comun</span></p><p><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff;\">Ejemplo: 5</span><span style=\" font-family:\'KaTeX_Math\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff;\">x</span><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff;\">+5</span><span style=\" font-family:\'KaTeX_Math\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff;\">y</span><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff;\">=5(</span><span style=\" font-family:\'KaTeX_Math\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff;\">x</span><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff;\">+</span><span style=\" font-family:\'KaTeX_Math\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff;\">y</span><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff;\">)</span></p></body></html>"))
        self.label_4.setText(_translate("VentanaBloque1_2", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Datos</span></p><p align=\"center\"><br/></p></body></html>"))
        self.CmdResolver.setText(_translate("VentanaBloque1_2", "Resolver"))
        self.label_5.setText(_translate("VentanaBloque1_2", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Resultado</span></p><p align=\"center\"><br/></p></body></html>"))
        self.label_6.setText(_translate("VentanaBloque1_2", "<html><head/><body><p><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff;\">Binomio Cuadrado Perfecto</span></p><p><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff;\">Ejemplo: (2x+4)</span><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff; vertical-align:super;\">2 </span><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff; vertical-align:sub;\">= </span><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff;\">4x</span><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff; vertical-align:super;\">2</span><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff;\">+16x+16</span><span style=\" font-family:\'KaTeX_Main,Times New Roman,serif\'; font-size:14pt; font-weight:600; color:#000000; background-color:#ffffff; vertical-align:super;\"><br/></span></p></body></html>"))
        self.CmdResolver2.setText(_translate("VentanaBloque1_2", "Resolver"))
        self.label_7.setText(_translate("VentanaBloque1_2", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Resultado</span></p><p align=\"center\"><br/></p></body></html>"))
        self.label_8.setText(_translate("VentanaBloque1_2", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Datos</span></p><p align=\"center\"><br/></p></body></html>"))
        self.CmdRegresar.setText(_translate("VentanaBloque1_2", "Regresar"))

    def Resuelve1(self):
        try:
            # Convertir la expresión ingresada en un objeto sympy
            expresioninicial = self.TxtDatos.text()
            expresionsinespacio = expresioninicial.replace(" ", "")
            expresionsinespacio = expresionsinespacio.replace("^", "**")
            expresioncorregida = re.sub(r'([a-zA-Z])(?=[a-zA-Z])', r'\1*', expresionsinespacio)
            expresioncorregida = re.sub(r'([a-zA-Z])([a-zA-Z])', r'\1*\2', expresioncorregida)
            expresioncorregida = re.sub(r'(\d+)([a-zA-Z])', r'\1*\2', expresioncorregida)
            solution = sp.factor(expresioncorregida)
            #solution = sp.solve(expresion1cam)
            espaniol = str(solution)
            cadena = espaniol.replace("**", "^")
            cadena = cadena.replace("*", "")
            self.LblFactorComun.setText(cadena)

        except (sp.SympifyError, ValueError) as e:
            print(f"Error al procesar la expresión: {e}")


    def Resuelve2(self):
        try:
            # Convertir la expresión ingresada en un objeto sympy
            expresioninicial = self.TxtDatos2.text()
            #print(expresioninicial)
            expresionsinespacio = expresioninicial.replace(" ", "")
            #print(expresionsinespacio)
            expresionsinespacio = expresionsinespacio.replace("^", "**")
            #print(expresionsinespacio)
            expresioncorregida = re.sub(r'([a-zA-Z])(?=[a-zA-Z])', r'\1*', expresionsinespacio)
            expresioncorregida = re.sub(r'([a-zA-Z])([a-zA-Z])', r'\1*\2', expresioncorregida)
            #print(expresioncorregida)
            expresioncorregida = re.sub(r'(\d+)([a-zA-Z])', r'\1*\2', expresioncorregida)
            #print(expresioncorregida)
            expresioncorregida = sympy.expand(expresioncorregida)
            #print(expresioncorregida)
            #solution =  sympy.factor(expresioncorregida)
            #print("solucion", solution)
            #solution = sp.solve(expresion1cam)
            espaniol = str(expresioncorregida)
            cadena = espaniol.replace("**", "^")
            #print("cadena expuesta", cadena)
            cadena = cadena.replace("*", "")
            self.LblBinomio.setText(cadena)

        except (sp.SympifyError, ValueError) as e:
            print(f"Error al procesar la expresión: {e}")

    def CierraBloque1(self):
        self.close()  # Cierra la ventana actual
        self.ventana_principal1 = VentanaBloques.VentanaBloquesClass()  # Crea una nueva instancia de VentanaPrincipal
        self.ventana_principal1.show()  # Muestra la nueva ventana principal


def main():
    app = QtWidgets.QApplication(sys.argv)
    ventana = VentanaBloque1_Class()
    ventana.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    main()
